import Head from 'next/head'
import { Header } from '@/components/Header'
import { Main } from '../components/Main'

// Em caso de desincronização de classes entre o front e o server, "yarn cache clean".
export default function Home() {
  return (
    <>
      <Head>
        <title>Hackerbet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <Header />
        <Main />
      </>
    </>
  )
}
